apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium
  template:
    metadata:
      labels:
        app: selenium
    spec:
      containers:
      - name: selenium
        image: selenium/standalone-chrome:latest
        ports:
        - containerPort: 4444
---
apiVersion: v1
kind: Service
metadata:
  name: selenium
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 4444
  selector:
    app: selenium
